version: '2'

services:
    event-service:
        image: siarheikarpenka/event-service:1.0.0-SNAPSHOT
        container_name: event-service
        environment:
          - JAVA_OPTS=-Xms1024m -Xmx1736m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -Xloggc:garbage-collection.log
        restart: always
        mem_limit: 2048m
        ports:
          - 8080:8080
        networks:
          - event-service

networks:
  event-service:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.61.0.0/16